//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computing_eguipment
    {
        public Computing_eguipment()
        {
            this.CE_user = new HashSet<CE_user>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string price { get; set; }
        public string computing_power { get; set; }
    
        public virtual ICollection<CE_user> CE_user { get; set; }

        public override string ToString()
        {
            return Id.ToString() + " " + name + " PRICE: " + price + " POWER: " + computing_power;
        }
    }
}
